# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [ ]:
import numpy as np
np.__version__

'1.18.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape) #1차원 배열임을 알 수 있음
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0]=4
a1[1]=5
a1[2]=6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [ ]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]]]
            )
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)
#어떤 값들이 올지는 모른다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1)
#a1의 배열과 같은 모양으로 다 0으로 채운 배열 만들어줘

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
np.arange(0,30,2)
#range함수를 그대로 배열에서 활용해서 쓴다고 생각하면 된다. array로 만들어짐

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0,1,5)  #0~1까지 균등하게 5개로 나누어줘

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3,3))

array([[0.64106207, 0.89211554, 0.87945856],
       [0.64730232, 0.29073716, 0.9278873 ],
       [0.54161229, 0.80052032, 0.24806588]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0,10,(3,3))
#랜덤으로 정수만을 뽑아서 0~10사이의 숫자들로 3x3배열 만들어줘

array([[0, 6, 4],
       [2, 7, 4],
       [8, 9, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0,1,(3,3))
#노멀 -> 정규분포. 평균 표준편차를 주어주고 사이즈를 주어줌(3x3)

array([[-0.28637343,  1.43691302,  1.30247516],
       [ 0.17397944, -0.46133472,  0.66819321],
       [-1.59134395, -0.76751077,  0.44261011]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3,3)
#사이즈만 정해주고 유니폼 형태로 값이 출력된다.

array([[0.29774771, 0.33460247, 0.23133635],
       [0.54962513, 0.46099937, 0.26547   ],
       [0.91318437, 0.58498759, 0.62198261]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3,3)
#표준정규분포

array([[-0.11846191,  0.06225592,  1.09063748],
       [ 1.08513903, -0.42010227, -2.27042569],
       [-0.47973641,  2.09081606, -0.72284791]])

### 표준 데이터 타입

In [ ]:
np.zeros(20,dtype=int)
#int값

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3),dtype=bool)
#bool값은 0,1밖에 없는데 ones는 1으로 true이므로 true로 채워준다.

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3),1.0,dtype=float)
#float형(실수값)으로 채워진 배열이 생성된다.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [ ]:
date=np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)
#특정한 규칙에 따라 증가하는 수열 np.arange
#날짜를 계산 가능한 형태로 나타낼 수 있다.

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime=np.datetime64('2020-05-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-05-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)    #실제 배열의 값
  print("ndim:",array.ndim)   #차원
  print("shape:",array.shape)   #몇개인지
  print("dtype:",array.size)    #무슨 자료형을 쓰는지(ex. 정수,실수)
  print("itemsize:",array.itemsize)   #사용되는 자료형의 byte크기
  print("nbytes:",array.nbytes)   #전체 byte 크기
  print("strides:",array.strides)   #다음 차원으로 넘어가기 위해서 shape보다 size로 나타내는 단위
                                    #다음 차원으로 넘어가기 위해 8byte가 필요한 것을 알 수 있음(1차원이기 때문)

In [ ]:
array_info(a1)
#그함수를 이용하여 a1의 속성들을 다 알 수 있다.

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)
#2차원일때

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)
#3차원일때
'''streide에서 다음 차원으로 넘어갈때 72바이트 필요, 
더 작은 값들 안에서(다음 열로 넘어가기 위해서)는 24바이트 필요,
더더 작은 값들 안에서(다음 행으로 넘어가기 위해서)는 8바이트 필요'''

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


'streide에서 다음 차원으로 넘어갈때 72바이트 필요, \n더 작은 값들 안에서(다음 열로 넘어가기 위해서)는 24바이트 필요,\n더더 작은 값들 안에서(다음 행으로 넘어가기 위해서)는 8바이트 필요'

### 인덱싱(Indexing)

In [ ]:
#인덱싱은 배열에 대해서도 접근이 가능
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2]) #step이 2인 형태로 출력
print(a1[::-1]) #역으로 출력

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [ ]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
#선택의 여부를 불리언으로 지정
print(a1)
bi=[False, True, True, False, True]
print(a1[bi]) #True값만 출력된다
bi=[True, False, True,True,False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a2)
bi=np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True  True]
 [False  True False]
 [False False False]]
[2 3 5]


### 팬시 인덱싱(Fancy Indedxing)

In [ ]:
print(a1)
print([a1[0],a1[2]])
ind=[0,2]
print(a1[ind])
ind = np.array([[0,1],
               [2,0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [ ]:
print(a2)
row=np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1])
print(a2[2,col])
print(a2[row,1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1=np.insert(a1,0,10)
print(b1)
c1=np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
b2=np.insert(a2,1,10,axis=0) #1행에 모두 10으로 추가하여 채운다.
print(b2)
c2=np.insert(a2,1,10,axis=1) #1열에 모두 10으로 추가하여 채운다.
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0]=1
a1[1]=2
a1[2]=3
print(a1)
a1[:1]=9 #하나만 바꾸는 것이 아니라 슬라이싱에 해당하는 부분을 9로 바꿈
i=np.array([1,3,4])
a1[i]=0
print(a1)
a1[i] +=4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [ ]:
print(a2)
a2[0,0]=1
a2[1,1]=2
a2[2,2]=3
a2[0]=1
print(a2)
a2[1:,2]=9 #1행~2행의 2열(배열상에서는 2행~3행의 3열 위치)
print(a2)
row=np.array([0,1])
col=np.array([1,2])
a2[row,col]=0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1=np.delete(a1,1) #1번째 요소값 삭제
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [ ]:
print(a1)
b1=np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)
b2=np.delete(a2,1,axis=0)
print(b2)
c2=np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
#copy 배열복사
#리스트자료형은 실제배열의 복사본으로 슬라이싱 결과를 출력하는데 넘파이는 그렇지 않다.
print(a2[:2,:2])
a2_sub=a2[:2,:2] #copy를 붙이지 않으면 원본데이터에서와 동일한 위치의 메모리위치를 사용하기 때문에,
                 # 원본데이터의 요소들도 바뀐다
print(a2_sub)
a2_sub[:,1]=0
print(a2_sub)
print(a2) #원본데이터도 0으로 바뀌어 버렸다.

[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [ ]:
print(a2)
a2_sub_copy=a2[:2,:2].copy()    
#원본데이터가 바뀌지 않게 하려면 copy()를 사용해주면 된다.
print(a2_sub_copy)
a2_sub_copy[:,1]=1
print(a2_sub_copy)
print(a2)   #다른 메모리위치에 저장된 a2

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [ ]:
print(a2)
print(a2.T) #T를 통해 전치시킴

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.T)
#3차원 배열 전치시킴

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.swapaxes(0,1))   #0,1을 swap시킴
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [ ]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3)) #2차원 배열로 바뀐 것을 볼 수 있다.

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [ ]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])  #col으로

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize(5,2) #사이즈 크기는 바뀌지 않고 모양만 바뀜
print(n2)

[[3 4 4 2 4]
 [4 6 2 8 2]]
[[3 4]
 [4 2]
 [4 4]
 [6 2]
 [8 2]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5,5))
print(n2)
#남은 부분은 0으로 채워짐

[[3 4 4 2 4]
 [4 6 2 8 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [ ]:
n2.resize((3,3))
print(n2)
#사이즈를 줄이면 나머지 부분들은 삭제된다

[[3 4 4]
 [2 4 4]
 [6 2 8]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2=np.append(a2,b2)
print(c2)
#append하니까 1차원 배열로 바뀜(특정한 지정을 안해줄 때)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)
#열 형태로 아래로 붙음, axis=0일때

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)
#행 형태로 옆으로 붙음, axis=1일때

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1=np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
#2차원 형태로도 가능
a2=np.array([[1,2,3,],
             [4,5,6],])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [ ]:
np.vstack([a2,a2])    #vertical stack : 수직, 배열이 수직으로 붙는다.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [ ]:
np.hstack([a2,a2]) #수평으로, 옆으로 붙음

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [ ]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [ ]:
np.stack([a2,a2])
#2차원 형태였는데 3차원 형태로 바뀜

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [ ]:
#배열을 분할하는 split하는
a1=np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5]) #[5]를 기준으로 split된다.
print(b1,c1)
#여러개로도 split 할 수 있다.
b1, c1, d1, e1, f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [ ]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2, c2=np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [ ]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2, c2=np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [ ]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])   
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [ ]:
#1차원 + 2차원 배열 = 2차원
#1차원 배열이 2차원 배열의 형태에 맞춰서 2차원 형태로 더해져서 2차원 배열이 나온다.
#1행 + 1열 = 각 shape에 대한 값이 있다고 가정하고 더해진다.
a1=np.array([1,2,3])
print(a1)
print(a1+5)

a2 = np.arange(1,10).reshape(3,3)   
#arange()는 특정한 규칙에 따라 증가하는 수열! 이라는거 기억,, 나올때 마다 자꾸 까먹음
print(a2)
print(a1+a2)

b2=np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [ ]:
a1=np.arange(1,10)
print(a1)
print(a1+1)
print(np.add(a1,10))
print(a1-2)
print(np.subtract(a1,10))   #함수를 사용해서 빼줄수도 있다
print(-a1)
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a1,2))
print(a1//2)
print(np.floor_divide(a1,2))    #floor 내림
print(a1**2)    #지수
print(np.power(a1,2))
print(a1%2)   #2로 나눈 나머지
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [ ]:
a1=np.arange(1,10)
print(a1)
b1=np.random.randint(1,10,size=9)
print(b1)
print(a1+b1)
print(a1-b1)
print(a1*b1)  
print(a1/b1)  
print(a1//b1)   #floor (올림내림)
print(a1 ** b1) #지수연산(승)
# print(a1 ^ b1) -> ^ hat 기호는 XOR 연산에 사용
print(a1%b1)    #나머지연산

[1 2 3 4 5 6 7 8 9]
[1 8 8 9 9 6 3 3 4]
[ 2 10 11 13 14 12 10 11 13]
[ 0 -6 -5 -5 -4  0  4  5  5]
[ 1 16 24 36 45 36 21 24 36]
[1.         0.25       0.375      0.44444444 0.55555556 1.
 2.33333333 2.66666667 2.25      ]
[1 0 0 0 0 1 2 2 2]
[      1     256    6561  262144 1953125   46656     343     512    6561]
[0 2 3 4 5 0 1 2 1]


In [ ]:
#2차원
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.random.randint(1,10,size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 9 8]
 [7 2 7]
 [1 8 9]]
[[ 6 11 11]
 [11  7 13]
 [ 8 16 18]]
[[-4 -7 -5]
 [-3  3 -1]
 [ 6  0  0]]
[[ 5 18 24]
 [28 10 42]
 [ 7 64 81]]
[[0.2        0.22222222 0.375     ]
 [0.57142857 2.5        0.85714286]
 [7.         1.         1.        ]]
[[        1       512      6561]
 [    16384        25    279936]
 [        7  16777216 387420489]]
[[1 2 3]
 [4 1 6]
 [0 0 0]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-4  0  3  1  1]
[4 0 3 1 1]
[4 0 3 1 1]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [ ]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))
#제곱과 제곱근

[-4  0  3  1  1]
[16  0  9  1  1]
[       nan 0.         1.73205081 1.         1.        ]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [ ]:
a1=np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[8 1 1 2 6]
[2.98095799e+03 2.71828183e+00 2.71828183e+00 7.38905610e+00
 4.03428793e+02]
[256.   2.   2.   4.  64.]
[64  1  1  4 36]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[8 1 1 2 6]
[2.07944154 0.         0.         0.69314718 1.79175947]
[3.        0.        0.        1.        2.5849625]
[0.90308999 0.         0.         0.30103    0.77815125]


#### 삼각 함수(Trigonometrical Function)


In [ ]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x=[-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [ ]:
a2=np.random.randint(1,10,size=(3,3))
print(a2)
#sum은 2차원이므로 축을 정할 수 있다.
print(a2.sum(),np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))
#축을 정해주면 정해준 축대로 더해진다.

[[4 4 8]
 [7 6 8]
 [2 7 1]]
47 47
[13 17 17] [13 17 17]
[16 21 10] [16 21 10]


#### cumsum(): 누적합 계산

In [ ]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[ 4  8 16 23 29 37 39 46 47]
[[ 4  4  8]
 [11 10 16]
 [13 17 17]]
[[ 4  8 16]
 [ 7 13 21]
 [ 2  9 10]]


#### diff(): 차분 계산

In [ ]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[[ 0  4]
 [-1  2]
 [ 5 -6]]
[[ 3  2  0]
 [-5  1 -7]]
[[ 0  4]
 [-1  2]
 [ 5 -6]]


#### prod(): 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
602112
[ 56 168  64]
[128 336  14]


#### cumprod(): 누적곱 계산

In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[     4     16    128    896   5376  43008  86016 602112 602112]
[[  4   4   8]
 [ 28  24  64]
 [ 56 168  64]]
[[  4  16 128]
 [  7  42 336]
 [  2  14  14]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2=np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [21 21 21]
 [10 10 10]]
[[16 16 16]
 [21 21 21]
 [10 10 10]]


#### tensordot(): 텐서곱 계산

In [ ]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
47
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
[[16 16 16]
 [21 21 21]
 [10 10 10]]


#### cross(): 벡터곱

In [ ]:
x=[1,2,3]
y=[4,5,6]
print(np.cross(x,y))
#2x6-3x5=-3, 3x4-1x6=6,2x4-1x5=-3

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [21 21 21]
 [10 10 10]]
[[4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4]
 [8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [2 2 2 2 2 2 2 2 2]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]]


#### mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0)) #axis 중심축선, axes 축 -> 둘이 비슷한.. 같은거인거 같음
print(np.mean(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
5.222222222222222
[4.33333333 5.66666667 5.66666667]
[5.33333333 7.         3.33333333]


#### std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

#### var(): 분산 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

#### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
1
[2 4 1]
[4 6 1]


#### max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
8
[7 7 8]
[8 8 7]


#### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
8
[2 0 2]
[0 1 2]


#### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
2
[1 2 0]
[2 2 1]


#### median(): 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))

[[4 4 8]
 [7 6 8]
 [2 7 1]]
6.0
[4. 6. 8.]
[4. 7. 2.]


#### percentile(): 백분위 수



In [ ]:
a1=np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [ ]:
a2=np.array([[False,False,False],
            [False,True,True],
            [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [ ]:
a2=np.array([[False,False,False],
            [False,True,True],
            [False,True,True]])
#all은 다 True여야 True
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
False
[False False False]
[False False False]


### 비교 연산(Comparison Operators)


In [ ]:
a1=np.arange(1,10)
print(a1)
print(a1==5)    #5가 맞으면 T, 5가 아니면 F
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [ ]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(np.sum(a2>5,axis=0))
print(np.sum(a2>5,axis=1))
print(np.any(a2>5))
print(np.any(a2>5,axis=0))
print(np.any(a2>5,axis=1))
print(np.all(a2>5))
print(np.all(a2>5,axis=0))
print(np.all(a2>5,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [ ]:
a1=np.array([1,2,3,4,5])
print(a1)
b1=np.array([1,2,3,4,5])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 4 5]
[ True  True  True  True  True]


In [ ]:
a1=np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [ ]:
a2=np.arange(1,10).reshape(3,3)
print(a2)

print((a2>5) & (a2<8))
print(a2[(a2>5) & (a2<8)])

print((a2>5) | (a2<8))
print(a2[(a2>5) | (a2<8)])

print((a2>5) ^ (a2<8))
print(a2[(a2>5) ^ (a2<8)])

print(~(a2>5))
print(a2[~(a2>5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [ ]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)

#정렬을 할떄 어느 위치에 와야할지
print(a1.sort())
print(a1)

[4 1 9 6 7 2 7 8 4 6]
[1 2 4 4 6 6 7 7 8 9]
[4 1 9 6 7 2 7 8 4 6]
[1 5 0 8 3 9 4 6 7 2]
[4 1 9 6 7 2 7 8 4 6]
None
[1 2 4 4 6 6 7 7 8 9]


In [ ]:
a2=np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[4 1 1]
 [9 7 5]
 [7 8 6]]
[[4 1 1]
 [7 7 5]
 [9 8 6]]
[[1 1 4]
 [5 7 9]
 [6 7 8]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [ ]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))   #작은값 순으로 3개를 뽑아줘

[1 1 6 5 8 2 1 2 5 5]
[1 1 1 2 2 5 5 5 6 8]


## 배열 입출력


In [ ]:
a2=np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))
#partition기능

[[6 4 9 6 1]
 [7 5 2 9 4]
 [8 5 2 6 4]
 [8 4 8 3 7]
 [8 4 9 5 1]]
[[4 1 6 6 9]
 [2 4 5 7 9]
 [2 4 5 6 8]
 [3 7 4 8 8]
 [5 1 4 8 9]]
[[7 4 8 3 1]
 [6 4 2 5 1]
 [8 4 2 6 4]
 [8 5 9 6 4]
 [8 5 9 9 7]]
[[4 1 6 6 9]
 [2 4 5 7 9]
 [2 4 5 6 8]
 [3 7 4 8 8]
 [5 1 4 8 9]]


In [ ]:
a2=np.random.randint(1,10,size=(5,5))
print(a2)
np.save("a",a2)

[[6 1 5 9 7]
 [1 5 9 7 7]
 [6 8 8 4 7]
 [9 1 9 5 1]
 [7 5 3 1 3]]


In [ ]:
!ls

a.npy  sample_data


In [ ]:
b2=np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab",a2,b2)

[[9 5 3 3 6]
 [4 1 1 6 5]
 [2 2 2 4 9]
 [7 3 4 9 2]
 [7 4 4 9 5]]


In [ ]:
!ls

ab.npz	a.npy  sample_data


In [ ]:
npy=np.load("a.npy")
print(npy)

[[6 1 5 9 7]
 [1 5 9 7 7]
 [6 8 8 4 7]
 [9 1 9 5 1]
 [7 5 3 1 3]]


In [ ]:
npz=np.load("ab.npz")
#여러개파일저장
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[6 1 5 9 7]
 [1 5 9 7 7]
 [6 8 8 4 7]
 [9 1 9 5 1]
 [7 5 3 1 3]]
[[9 5 3 3 6]
 [4 1 1 6 5]
 [2 2 2 4 9]
 [7 3 4 9 2]
 [7 4 4 9 5]]


In [ ]:
#텍스트로 저장하고 싶을때
print(a2)
np.savetxt("a.csv",a2,delimiter=',')

[[6 1 5 9 7]
 [1 5 9 7 7]
 [6 8 8 4 7]
 [9 1 9 5 1]
 [7 5 3 1 3]]


In [ ]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [ ]:
!cat a.csv

6.000000000000000000e+00,1.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00
1.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,7.000000000000000000e+00
6.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00,7.000000000000000000e+00
9.000000000000000000e+00,1.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00,1.000000000000000000e+00
7.000000000000000000e+00,5.000000000000000000e+00,3.000000000000000000e+00,1.000000000000000000e+00,3.000000000000000000e+00


In [ ]:
csv = np.loadtxt("a.csv",delimiter=',')
print(csv)

[[6. 1. 5. 9. 7.]
 [1. 5. 9. 7. 7.]
 [6. 8. 8. 4. 7.]
 [9. 1. 9. 5. 1.]
 [7. 5. 3. 1. 3.]]


In [ ]:
print(b2)
np.savetxt("b.csv",b2,delimiter=',',fmt='%.2e',header='c1,c2,c3,c4,c5')

[[9 5 3 3 6]
 [4 1 1 6 5]
 [2 2 2 4 9]
 [7 3 4 9 2]
 [7 4 4 9 5]]


In [ ]:
!cat b.csv

# c1,c2,c3,c4,c5
9.00e+00,5.00e+00,3.00e+00,3.00e+00,6.00e+00
4.00e+00,1.00e+00,1.00e+00,6.00e+00,5.00e+00
2.00e+00,2.00e+00,2.00e+00,4.00e+00,9.00e+00
7.00e+00,3.00e+00,4.00e+00,9.00e+00,2.00e+00
7.00e+00,4.00e+00,4.00e+00,9.00e+00,5.00e+00


In [ ]:
csv=np.loadtxt('b.csv',delimiter=',')
print(csv)

[[9. 5. 3. 3. 6.]
 [4. 1. 1. 6. 5.]
 [2. 2. 2. 4. 9.]
 [7. 3. 4. 9. 2.]
 [7. 4. 4. 9. 5.]]




---

