In [ ]:
import numpy as np

In [ ]:
def sigmoid(X):
  return 1 / (1 + np.exp(-X))

In [ ]:
X = np.array([1.0, 0.5, 0.4, 0.6, 0.9])
W1 = np.array([[1.1, 1.2, 1.3, 1.4, 1.5], [2.0, 1.8, 1.6, 1.4, 1.2], [1.1, 1.2, 1.3, 1.4, 1.5], [1.3, 1.6, 1.9, 2.2, 2.5], [0.4, 0.6, 0.8, 1.0, 1.2]])
B1 = np.array([1,1,1,1,1])


print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) +B1
Z1 = sigmoid(A1)

print(A1)
print(Z1)

(5, 5)
(5,)
(5,)
[4.68 5.08 5.48 5.88 6.28]
[0.99080629 0.99381854 0.99584798 0.997213   0.9981301 ]


In [ ]:
W2 = np.array([[1.1, 1.2, 1.3, 1.4, 1.5], [0.3, 0.5, 0.7, 0.9, 1.1], [1.3, 1.6, 1.9, 2.2, 2.5], [0.7, 0.6, 0.5, 0.4, 0.3], [0.1, 0.3, 0.5, 0.7, 0.9]])
B2 = np.array([1,1,1,1,1])

print(W2.shape)
print(B2.shape)

A2 = np.dot(A1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

(5, 5)
(5,)
[19.54  23.336 27.132 30.928 34.724]
[1. 1. 1. 1. 1.]


In [ ]:
W3 = np.array([[1.2, 1.3, 1.4, 1.5], [0.9, 0.7, 0.4, 0.2], [0.4, 0.3, 0.2, 0.1], [0.25, 0.5, 0.75, 1.0], [0.9, 0.8, 0.7, 0.6]])
B3 = np.array([1,1,1,1])

print(W3.shape)
print(B3.shape)

A3 = np.dot(A2, W3) + B3
Z3 = sigmoid(A3)

print(A3)
print(Z3)

(5, 4)
(4,)
[95.2868 94.12   90.6196 89.4528]
[1. 1. 1. 1.]


In [ ]:
W4 = np.array([[0.1, 0.2, 0.3], [0.3, 0.5, 0.7], [0.3, 0.5, 0.7], [1.1, 1.2, 1.3]])
B4 = np.array([1,1,1])

print(W4.shape)
print(B4.shape)

A4 = np.dot(A3, W4) + B4
Y = sigmoid(A4)

print(A4)
print(Y)

(4, 3)
(3,)
[164.34864 219.77052 275.1924 ]
[1. 1. 1.]


In [ ]:
W5 = np.array([[0.1, 0.3], [0.3, 0.7], [0.3, 0.7]])
B5 = np.array([1,1])

print(W5.shape)
print(B5.shape)

A5 = np.dot(A4, W5) + B5
Y = sigmoid(A5)

print(A5)
print(Y)

(3, 2)
(2,)
[165.92374  396.778636]
[1. 1.]


In [ ]:
W6 = np.array([[0.1, 0.2], [1.5, 2.0]])
B6 = np.array([1,1])

print(W6.shape)
print(B6.shape)

A6 = np.dot(A5, W6) + B6
Y = sigmoid(A6)

print(A6)
print(Y)

(2, 2)
(2,)
[612.760328 827.74202 ]
[1. 1.]


In [ ]:
def network():

  network = {}

  #첫번째 레이어
  network['W1'] = np.array([[1.1, 1.2, 1.3, 1.4, 1.5], [2.0, 1.8, 1.6, 1.4, 1.2], [1.1, 1.2, 1.3, 1.4, 1.5], [1.3, 1.6, 1.9, 2.2, 2.5], [0.4, 0.6, 0.8, 1.0, 1.2]])
  network['B1'] = np.array([1,1,1,1,1])

  #두번째 레이어
  network['W2'] = np.array([[1.1, 1.2, 1.3, 1.4, 1.5], [0.3, 0.5, 0.7, 0.9, 1.1], [1.3, 1.6, 1.9, 2.2, 2.5], [0.7, 0.6, 0.5, 0.4, 0.3], [0.1, 0.3, 0.5, 0.7, 0.9]])
  network['B2'] = np.array([1,1,1,1,1])

  #세번째 레이어
  network['W3'] =np.array([[1.2, 1.3, 1.4, 1.5], [0.9, 0.7, 0.4, 0.2], [0.4, 0.3, 0.2, 0.1], [0.25, 0.5, 0.75, 1.0], [0.9, 0.8, 0.7, 0.6]])
  network['B3'] = np.array([1,1,1,1])

  #네번째 레이어
  network['W4'] = np.array([[0.1, 0.2, 0.3], [0.3, 0.5, 0.7], [0.3, 0.5, 0.7], [1.1, 1.2, 1.3]])
  network['B4'] = np.array([1,1,1])

  #다섯번째 레이어
  network['W5'] = np.array([[0.1, 0.3], [0.3, 0.7], [0.3, 0.7]])
  network['B5'] = np.array([1,1])

  #여섯번째 레이어
  network['W6'] = np.array([[0.1, 0.2], [1.5, 2.0]])
  network['B6'] = np.array([1,1])

  return network

In [ ]:
def forward(network, x):
  W1, W2, W3, W4, W5, W6 = network['W1'], network['W2'], network['W3'], network['W4'], network['W5'], network['W6']
  B1, B2, B3, B4, B5, B6 = network['B1'], network['B2'], network['B3'], network['B4'], network['B5'], network['B6']

  A1 = np.dot(x, W1) + B1
  Z1 = sigmoid(A1)

  A2 = np.dot(Z1, W2) + B2
  Z2 = sigmoid(A2)

  A3 = np.dot(Z2, W3) + B3
  Z3 = sigmoid(A3)

  A4 = np.dot(Z3, W4) + B4
  Z4 = sigmoid(A4)

  A5 = np.dot(Z4, W5) + B5
  Z5 = sigmoid(A5)

  A6 = np.dot(Z5, W6) + B6
  y = sigmoid(A6)

  return y

In [ ]:
net = network()
x = np.array([0.3, 1.3, -2.2, 0.5, 0.7])
y = forward(net, x)
print(y)

[0.92307906 0.95417849]
